### ISSUE TITLE
Port to 1.18.x

### ISSUE THREAD

**Issue by TalEdd** [joaoh1/ARRFAB#3]
Any chance that this mod will be updating to 1.18+, would love to have this feature in the newer Minecraft versions too!

**Comment by EnnuiL** [comment]
There are plans to drastically overhaul this mod for the 1.19 era, with it perhaps being a good showcase of a new WIP API of mine;
Unfortunately, I've been busy with both IRL and also with other projects, so yeah, while I don't expect to work on this mod soon, I do hope to revisit it some day

**Comment by EnnuiL** [comment]
Oh, I just remembered:
For now, [WTHIT's REI support](https://www.curseforge.com/minecraft/mc-mods/wthit) does cover this functionality if you need something like that now, however, yeah, I still want to maintain this mod as an independent bridge that could take advantage of different lookup mods and interface with different recipe viewer ones; After all, a Fabric port of The One Probe does exist, and it would be nice to have some sort of integration with it
(and plus, I love having the View Recipes/Usage key binds' defaults as PageUp/Down :P)
